Edit the current Device Settings
---
tags:
  - device
consumes:
  - application/json
produces:
  - application/json
  - application/xml
parameters:
  - in: header
    name: x-access-token
    description: JWT received after succussful login.
    type: string
    required: true
  - in: body
    name: body
    description: New Device Settings
    required: true
    schema:
      $ref: '#/definitions/DeviceSettings'
responses:
  200:
    description: OK
    schema:
      $ref: '#/definitions/DeviceSettings'